"""Add dialog_id to chat_history

Revision ID: 39478d2da104
Revises: 3688231a2c84
Create Date: 2025-06-12 06:50:11.994407+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39478d2da104'
down_revision = '3688231a2c84'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_history', sa.Column('dialog_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_chat_history_dialog_id'), 'chat_history', ['dialog_id'], unique=False)
    op.add_column('task_logs', sa.Column('task_id', sa.String(length=36), nullable=True))
    op.add_column('task_logs', sa.Column('result', sa.Text(), nullable=True))
    op.create_index(op.f('ix_task_logs_task_id'), 'task_logs', ['task_id'], unique=False)
    op.drop_column('task_logs', 'task_name')
    op.drop_column('task_logs', 'message')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_logs', sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('task_logs', sa.Column('task_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_task_logs_task_id'), table_name='task_logs')
    op.drop_column('task_logs', 'result')
    op.drop_column('task_logs', 'task_id')
    op.drop_index(op.f('ix_chat_history_dialog_id'), table_name='chat_history')
    op.drop_column('chat_history', 'dialog_id')
    # ### end Alembic commands ### 